apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{APP_NAME}}
spec:
  serviceName: {{APP_NAME}}
  replicas: {{REPLICAS}}
  template:
    metadata:
      labels:
        app: {{APP_NAME}}
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: {{APP_NAME}}
        image: {{IMAGE_NAME}}
        ports:
        - containerPort: 8125
          name: incoming-udp
          protocol: UDP
